version: 2

app_config: &app_config
    docker:
        - image: circleci/php:7.3-stretch-node-browsers

jobs:
  build:
    <<: *app_config

    steps:
        - checkout
        - run: 
            name: Show setup
            command: echo "Setup imenoga"

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
